- added a destroy-script for the resources installed
kubernetes-csi/csi-driver-host-path pull request #216
Opened 2020-11-09 20:01 UTC by aayushrangwala

- added labels to the resources

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Need a cleanup script to delete all the installed resources

**Which issue(s) this PR fixes**:
Fixes https://github.com/kubernetes-csi/csi-driver-host-path/issues/212

**Does this PR introduce a user-facing change?**:
NONE

```release-note
All the csi resources from k8s 1.17 will be having a common label `partof: csi-hostpath-driver` which will be used to collectively identify all the resources under csi installation and also can be used to delete them in bulk
```

2020-11-09 20:49 UTC, aayushrangwala commented
/cc @pohly

2020-11-10 10:05 UTC, pohly requested changes

2020-11-10 10:05 UTC, pohly commented on deploy/util/destroy-hostpath.sh
> +LABELS=(csi-snapshotter csi-hostpathplugin csi-attacher csi-resizer csi-hostpath-driver csi-provisioner csi-hostpath-socat)
The labels have to be specific to the hostpath deployment. We cannot risk deleting something that may be part of some other CSI driver deployment.

The setup script has to add those labels instead of assuming that the sidecar RBAC objects already have certain labels. When the script was originally written, kustomize was still new. It might be possible to rely on the kustomize in kubectl >= 1.17 to add labels. Even the image selection might now be done that way.

2020-11-10 10:36 UTC, aayushrangwala commented on deploy/util/destroy-hostpath.sh
> +LABELS=(csi-snapshotter csi-hostpathplugin csi-attacher csi-resizer csi-hostpath-driver csi-provisioner csi-hostpath-socat)
Right. Makes more sense. I believe using kustomize across the project is in the scope of another ticket. But I will note your point and change the labels and maybe create a new pr for the kustomize

2020-11-16 10:18 UTC, pohly commented on .gitignore
> +# Dependency directories (remove the comment below to include it)
In your next push, please also clean up your commit:
- don't change .gitignore
- use a commit message that has a subject line and a body (separated by blank line) which explains what this is about and why the change is relevant

2021-01-26 07:32 UTC, pohly commented on .gitignore
> +# Dependency directories (remove the comment below to include it)
@aayushrangwala do you want to finish this PR?

2021-04-15 07:51 UTC, aayushrangwala commented on .gitignore
> +# Dependency directories (remove the comment below to include it)
@pohly Yeah, I will wrap this up. Got stuck in something completely unaboidable

2021-04-15 07:52 UTC, aayushrangwala commented on .gitignore
> +# Dependency directories (remove the comment below to include it)
cleaned commit

2021-04-15 20:38 UTC, pohly commented on deploy/util/destroy-hostpath.sh
> +LABELS=(csi-hostpath-snapshotter csi-hostpathplugin csi-hostpath-attacher csi-hostpath-resizer csi-hostpath-driver csi-hostpath-provisioner csi-hostpath-socat)
These labels are both not specific enough (are they guaranteed to be unique?!) and too complex. Consider https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/.

What we should be using is:
```
app.kubernetes.io/instance: hostpath.csi.k8s.io
app.kubernetes.io/part-of: csi-driver-host-path
```

Here `hostpath.csi.k8s.io` is the CSI driver name which is guaranteed to be unique in the cluster.

There are others that might make sense (like `app.kubernetes.io/name` and `app.kubernetes.io/component` to describe individual parts, e.g. `name: external-provisioner`, `component: provisioner`) but we don't need them for cleaning up.

With those two labels, we don't need to iterate over multiple labels when deleting.

2021-04-15 20:40 UTC, pohly commented on deploy/util/destroy-hostpath.sh
> +# snapshotter, resizer, socat and hostpath plugin in the default namespace.
Instead of this logic here, you can add deleting of pods and use `kubectl delete --wait=true` for everything.

2021-04-15 20:42 UTC, pohly commented on deploy/util/destroy-hostpath.sh
> +# snapshotter, resizer, socat and hostpath plugin in the default namespace.
Throw in `--cascade=foreground` and deleting a daemonset will wait for pods to be deleted. Deleting the pods then becomes a safeguard that shouldn't be needed.

2021-04-15 20:43 UTC, pohly commented on deploy/util/destroy-hostpath.sh
> +    done
I don't think we need this.

2021-04-16 05:01 UTC, aayushrangwala commented on deploy/util/destroy-hostpath.sh
> +LABELS=(csi-hostpath-snapshotter csi-hostpathplugin csi-hostpath-attacher csi-hostpath-resizer csi-hostpath-driver csi-hostpath-provisioner csi-hostpath-socat)
Great!. Its way more suitable. made that change

2021-04-16 06:51 UTC, aayushrangwala commented on deploy/util/destroy-hostpath.sh
> +    done
Added that as a fallback. Can remove it

2021-04-16 07:16 UTC, pohly commented on deploy/util/destroy-hostpath.sh
> +    done
Please do. If deleting by label somehow is incomplete, we should fix that instead of pampering over the problem with a fallback.

2021-04-16 08:46 UTC, aayushrangwala commented on deploy/util/destroy-hostpath.sh
> +    done
Also adding the logic to delete rbacs. Since we install it using external (version calculated) files, we might have to delete them the same way as they dont have the required labels. Otherwise we have to add PRs on independent sidecars to add labels on all of their resources.

2021-04-16 10:00 UTC, pohly commented on deploy/util/destroy-hostpath.sh
> +    done
We can add labels when creating the RBAC objects. It makes the deploy script a bit more complicated, but the result then is consistent.

Using kustomize instead of the hand-crafted shell script is also an option.

2021-04-24 14:55 UTC, aayushrangwala commented on deploy/util/destroy-hostpath.sh
> +# snapshotter, resizer, socat and hostpath plugin in the default namespace.
Added the change

2021-04-24 14:56 UTC, aayushrangwala commented on deploy/util/destroy-hostpath.sh
> +    done
@pohly Added the labels to rbac

2021-04-25 18:57 UTC, aayushrangwala commented on deploy/util/destroy-hostpath.sh
> +LABELS=(csi-snapshotter csi-hostpathplugin csi-attacher csi-resizer csi-hostpath-driver csi-provisioner csi-hostpath-socat)
Resolved them. Please re-review

2021-04-26 06:31 UTC, pohly commented
/ok-to-test

2021-04-26 06:43 UTC, aayushrangwala commented
/retest

2021-04-26 06:44 UTC, pohly requested changes

2021-04-26 06:44 UTC, pohly commented on deploy/util/destroy-hostpath.sh
> +# snapshotter, resizer, socat and hostpath plugin in the default namespace.
The more I look at this less convinced I am that we should have the code for deleting pods.

Grepping by name is going to fail if in the (unlikely, but not impossible) scenario that there are multiple deployments and we simply shouldn't need this.

2021-04-26 06:44 UTC, pohly commented on deploy/util/destroy-hostpath.sh
> +kubectl delete all -l app.kubernetes.io/instance=hostpath.csi.k8s.io,app.kubernetes.io/part-of=csi-driver-host-path --wait=true --timeout=60s --cascade=foreground
Please add `--all-namespaces` to both commands.

Can you also spell out the object types instead of using the shorthands? This is going to be read more often than being written, and at least I had to stop and think about what "sa" and "sts" stand for.

2021-04-26 06:44 UTC, pohly commented on deploy/util/destroy-hostpath.sh
> +kubectl delete all -l app.kubernetes.io/instance=hostpath.csi.k8s.io,app.kubernetes.io/part-of=csi-driver-host-path --wait=true --timeout=60s --cascade=foreground
Please add a comment in the script about why some objects get deleted explicitly and others not.

2021-04-26 06:44 UTC, pohly commented on deploy/util/destroy-hostpath.sh
> +BASE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
No need to depend on bash here.
Please use the same stanza as in `deploy-hostpath.sh`:
```
BASE_DIR="$( cd "$( dirname "$0" )" && pwd )"
```

2021-04-26 07:02 UTC, aayushrangwala commented on deploy/util/destroy-hostpath.sh
> +BASE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
Not needed because I removed the pod deletion logic

2021-04-26 07:09 UTC, aayushrangwala commented on deploy/util/destroy-hostpath.sh
> +kubectl delete all -l app.kubernetes.io/instance=hostpath.csi.k8s.io,app.kubernetes.io/part-of=csi-driver-host-path --wait=true --timeout=60s --cascade=foreground
Added `--all-namespaces` and the comment. Also removed the deletion of pods based on grep, although the same logic is there in the deploy script to check if the pods are not up for each component

2021-04-26 07:31 UTC, aayushrangwala commented
/retest

2021-04-26 07:58 UTC, pohly commented on deploy/util/deploy-hostpath.sh
> +    cat <<- EOF > ./kustomization.yaml
We don't know where this script runs and shouldn't blindly overwrite the kustomization.yaml file there.

Please use `mktemp -d` to create a temporary directory at the start of this script with an exit trap to clean it up.

2021-04-26 08:39 UTC, aayushrangwala commented on deploy/util/deploy-hostpath.sh
> +    cat <<- EOF > ./kustomization.yaml
made the changes. Please check

2021-04-26 09:26 UTC, pohly requested changes

2021-04-26 09:26 UTC, pohly commented on deploy/util/deploy-hostpath.sh
> +echo "creating temp directory"
I don't think we need to print this.

2021-04-26 09:26 UTC, pohly commented on deploy/util/deploy-hostpath.sh
> +rm -rf "${TEMP_DIR}"
A better way to do this is via an exit trap. Then the cleanup happens also when aborting with CTRL-C.

See above.

2021-04-26 09:26 UTC, pohly commented on deploy/util/deploy-hostpath.sh
> +TEMP_DIR="$( mktemp -d )"
Add here:
```
trap 'rm -r $TEMP_DIR' EXIT
```

2021-04-26 09:31 UTC, pohly requested changes

2021-04-26 09:31 UTC, pohly commented on deploy/util/deploy-hostpath.sh
> +    curl "${current}" --output rbac.yaml
`${current}` might be a file when used for testing the sidecar repo which contains the RBAC file.

 `kubectl` handles that, curl doesn't. You need to add a check for that here and only download if it is a URL.

Please also add `--silent --location` to the curl invocation.

2021-04-26 09:31 UTC, pohly commented on deploy/util/deploy-hostpath.sh
> +    run rm "${TEMP_DIR}"/kustomization.yaml
You can remove this `rm`.

2021-04-26 10:51 UTC, aayushrangwala commented on deploy/util/deploy-hostpath.sh
> +echo "creating temp directory"
got it

2021-04-26 10:51 UTC, aayushrangwala commented on deploy/util/deploy-hostpath.sh
> +rm -rf "${TEMP_DIR}"
right, skipped my mind. Added

2021-04-26 15:22 UTC, aayushrangwala commented on deploy/util/deploy-hostpath.sh
> +    curl "${current}" --output rbac.yaml
Good point. Added

2021-04-26 15:22 UTC, aayushrangwala commented on deploy/util/deploy-hostpath.sh
> +    run rm "${TEMP_DIR}"/kustomization.yaml
got it. removed

2021-04-26 15:23 UTC, aayushrangwala commented on deploy/util/deploy-hostpath.sh
> +TEMP_DIR="$( mktemp -d )"
done

2021-04-26 16:07 UTC, pohly requested changes

2021-04-26 16:07 UTC, pohly commented on deploy/util/deploy-hostpath.sh
> +    fi
... and this `rbac.yaml` gets used where?

2021-04-26 16:13 UTC, aayushrangwala commented on deploy/util/deploy-hostpath.sh
> +    fi
My bad. Skipped one commit to push. Will add the comment as well and push again

2021-04-27 08:54 UTC, pohly requested changes
Can you also update deploy/kubernetes-distributed?

The deploy.sh script there is a fork, but your changes apply with some offsets:
```
$ git diff origin/master..HEAD deploy/util/deploy-hostpath.sh | patch deploy/kubernetes-distributed/deploy.sh
patching file deploy/kubernetes-distributed/deploy.sh
Hunk #1 succeeded at 13 with fuzz 2 (offset -14 lines).
Hunk #2 succeeded at 137 with fuzz 1 (offset -31 lines).
```

2021-04-27 08:54 UTC, pohly commented on deploy/kubernetes-1.20/hostpath/csi-hostpath-plugin.yaml
> +    app.kubernetes.io/component: plugin
Those labels also should be set inside the PodSpec, otherwise `kubectl get all -l     app.kubernetes.io/instance=hostpath.csi.k8s.io` returns an incomplete result.


I think it is okay to use the same key/value pairs as for the StatefulSet itself.

The same change is needed also for the other StatefulSets and DaemonSets.

2021-04-27 08:54 UTC, pohly commented on deploy/util/deploy-hostpath.sh
> +    echo "adding labels to rbac"
I ran this script and did not fine this line useful. Can you remove it?

2021-04-27 08:54 UTC, pohly commented on deploy/util/deploy-hostpath.sh
> +      curl "${current}" --output "${TEMP_DIR}"/rbac.yaml --silent --location
More important is to wrap this with `run`, because then it will be obvious what failed if curl prints error messages.

2021-05-01 16:37 UTC, aayushrangwala commented on deploy/kubernetes-1.20/hostpath/csi-hostpath-plugin.yaml
> +    app.kubernetes.io/component: plugin
Yeah makes sense it will make the child pods for the app object distinguishable

2021-05-01 16:38 UTC, aayushrangwala commented on deploy/util/deploy-hostpath.sh
> +    echo "adding labels to rbac"
removed

2021-05-01 16:38 UTC, aayushrangwala commented on deploy/util/deploy-hostpath.sh
> +      curl "${current}" --output "${TEMP_DIR}"/rbac.yaml --silent --location
right.

2021-05-01 17:38 UTC, aayushrangwala commented
/retest

2021-05-02 08:37 UTC, aayushrangwala commented
/retest

2021-05-03 08:54 UTC, pohly requested changes
One last fix and then it should be ready.

Please also squash all commits.

2021-05-03 08:54 UTC, pohly commented on deploy/kubernetes-distributed/destroy.sh
> +kubectl delete role,clusterrole,rolebinding,clusterrolebinding,serviceaccount,storageclass --all-namespaces -l app.kubernetes.io/instance=hostpath.csi.k8s.io,app.kubernetes.io/part-of=csi-driver-host
`csidriver` must be added here.

2021-05-03 09:15 UTC, aayushrangwala commented on deploy/kubernetes-distributed/destroy.sh
> +kubectl delete role,clusterrole,rolebinding,clusterrolebinding,serviceaccount,storageclass --all-namespaces -l app.kubernetes.io/instance=hostpath.csi.k8s.io,app.kubernetes.io/part-of=csi-driver-host
Done

2021-05-03 10:21 UTC, pohly approved these changes
/lgtm
/approve

Thanks for the contribution.

2021-05-03 10:22 UTC, merged