Volume size
kubernetes-csi/csi-driver-host-path pull request #253
Opened 2021-03-08 14:48 UTC by pohly

**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:

More complete storage capacity simulation.

**Does this PR introduce a user-facing change?**:
```release-note
The hostpath driver now has a configurable fixed maximum volume size. It reports the minimum of that and the remaining capacity as `GetCapacityResponse.MaximumVolumeSize`. `GetCapacityResponse.MinimumVolumeSize` is always zero.
```

2021-04-08 18:29 UTC, pohly commented
@avalluri I took some of your commits from PR #269, added some fixes and rewrote the capacity tracking as I mentioned there.

Can you perhaps review this PR?

2021-04-08 18:30 UTC, pohly commented
/test pull-kubernetes-csi-csi-driver-host-path-distributed-on-kubernetes-master

This job is relevant because that is where the driver gets deployed with capacity tracking. It's still experimental and therefore not enabled by default.

2021-04-08 19:22 UTC, pohly commented
/test pull-kubernetes-csi-csi-driver-host-path-distributed-on-kubernetes-master

2021-04-08 20:25 UTC, avalluri commented
/lgtm

2021-04-08 20:25 UTC, avalluri commented
> Can you perhaps review this PR?

Looks good to me.

2021-04-08 23:23 UTC, verult commented
/assign

2021-04-15 07:33 UTC, verult requested changes
LGTM otherwise! Sorry for the delay

2021-04-15 07:33 UTC, verult commented on pkg/hostpath/capacity.go
> -func (c *Capacity) Alloc(kind string, size int64) (actualKind string, err error) {
This whole commit is pretty great! Much simpler

2021-04-15 07:57 UTC, verult commented
/lgtm
/hold

Since this PR is blocking a few other ones, please feel free to cancel the hold and address the remaining comments in a separate PR if needed.

2021-04-15 09:09 UTC, pohly commented on pkg/hostpath/capacity.go
> +		*c = Capacity{}
> Pre-allocating memory for an empty map might be better comparing to opening up risks for panics?

That's what I did earlier in https://github.com/kubernetes-csi/csi-driver-host-path/blob/97346865ff2d0e890db424bdbf165f46522dc6a1/cmd/hostpathplugin/main.go#L45

Then someone else removed that line without realizing that it is needed, leading to a panic when setting the parameter. It would be nicer if a default-initialized `Capacity` (= `nil` map instead of `map[string]resource.Quantity{}`) just worked, which is what I am trying to achieve here.

> if c is nil then *c == nil results in a panic. It's easy for others working on this code to make a mistake.

How can c be nil? Someone would have to explicitly declare a pointer to a `Capacity` and then call `Set` for that pointer. That is not something that I would expect to work unless explicitly documented for a type, so I think panicking in that case is fine.

2021-04-15 09:18 UTC, pohly commented on cmd/hostpathplugin/main.go
> +	flag.Int64Var(&cfg.MaxVolumeSize, "maxvolumesize", 1024*1024*1024*1024, "maximum size of volumes in bytes")
Fixed.

2021-04-15 09:22 UTC, pohly commented on pkg/hostpath/controllerserver.go
> +		maxVolumeSize = available
The comparison is indeed backwards. I really wish Go had a `min(a,b)` template function :cry: 

Fixed. I did not add a log message for this though, because the result should be obvious also without it.

2021-04-15 09:24 UTC, pohly commented on pkg/hostpath/capacity.go
> -func (c *Capacity) Alloc(kind string, size int64) (actualKind string, err error) {
Yes, I should have done it like that from the start. Oh well.

2021-04-15 09:25 UTC, pohly commented
@verult please take another look, I pushed the updated commits.

2021-04-15 09:25 UTC, pohly commented
/test pull-kubernetes-csi-csi-driver-host-path-distributed-on-kubernetes-master

2021-04-15 17:41 UTC, verult commented on pkg/hostpath/capacity.go
> +		*c = Capacity{}
Ah ok thanks for the context! nit: add a comment for the rationale in case anyone in the future wonders why this is done.

> How can c be nil? Someone would have to explicitly declare a pointer to a Capacity and then call Set for that pointer. That is not something that I would expect to work unless explicitly documented for a type, so I think panicking in that case is fine.
That's true, ack

2021-04-15 17:42 UTC, verult commented
/lgtm

Keeping hold in case you want to address the nit

2021-04-15 18:23 UTC, pohly commented on pkg/hostpath/capacity.go
> +		*c = Capacity{}
Added. Please review and LGTM.

2021-04-15 18:24 UTC, pohly commented
/hold cancel

2021-04-15 18:36 UTC, verult commented
/lgtm

2021-04-15 18:42 UTC, merged