Copy features from Mock CSI driver
kubernetes-csi/csi-driver-host-path pull request #260
Opened 2021-03-19 17:20 UTC by avalluri

**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
This enables in replacing the Mock CSI driver with host-path driver in Kubernetes E2E testing as described in #247 

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
- Added 'proxy' support; where the host-path driver offloads the CSI requests transparently to the external CSI driver running at `--proxy-endpoint`.
- Implemented Controller{Publish,Unpublish}Volume calls. Introduced a new command-line argument `--disable-attach` (defaults to `false`) which controls if the driver should add `RPC_PUBLISH_UNPUBLISH_VOLUME` to its controller capablilities.
- GRPC calls are logged in an unified(request, reply and error) JSON format.
```

2021-03-19 17:37 UTC, pohly commented
/ok-to-test

2021-03-22 14:26 UTC, pohly requested changes

2021-03-22 14:26 UTC, pohly commented on pkg/hostpath/server.go
> -	glog.V(5).Infof("GRPC request: %+v", protosanitizer.StripSecrets(req))
Let's keep the behavior at level 3 as it is:
- don't log `Probe`
- log as plain text as before

At level 5, we then *add* (not *replace*):
- plain text logging of `Probe`
- JSON output

`if klog.V(5).Enabled() { ... do JSON logging ... }` is a useful pattern for avoiding the overhead of formatting as JSON.

2021-03-22 14:26 UTC, pohly commented on go.sum
> -github.com/onsi/ginkgo v1.11.0 h1:JAKSXpt1YjtLA7YpPiqO9ss6sNXEsPfSGdwN0UHqzrw=
Do the go.sum changes really belong into this commit?

2021-03-22 14:26 UTC, pohly commented on cmd/hostpathplugin/main.go
> +	disableAttach = flag.Bool("disable-attach", false, "Disables RPC_PUBLISH_UNPUBLISH_VOLUME capability.")
`-disable-attach=false` is a double negation, which is harder to understand. Also considering that attach is not really doing anything useful (i.e. it's just for testing), I prefer `enable-attach` with false as default.

2021-03-22 14:26 UTC, pohly commented on pkg/hostpath/controllerserver.go
> +	topologies := []*csi.Topology{{
A useful enhancement, but better put it into a separate commit.

Nit: I prefer
```
topologies := []*csi.Topology{
    {Segments: map[string]string{TopologyKeyNode: hp.nodeID}},
}
```

2021-03-22 14:26 UTC, pohly commented on pkg/hostpath/controllerserver.go
> +	v.VolAttached = false
There is no check here?

2021-03-22 14:26 UTC, pohly commented on pkg/hostpath/controllerserver.go
> +	}
Which checks are needed in the other method calls when attaching is enabled?

I suppose
- NodePublishVolume without prior VolumePublishVolume must fail
- VolumeUnpublishVolume between NodePublishVolume and NodeUnpublishVolume must fail
- DeleteVolume between ControllerPublishVolume and ControllerUnpublishVolume must fail

2021-03-22 14:26 UTC, pohly commented on pkg/hostpath/controllerserver.go
> +	}
Check after this whether NodePublishVolume has been called without NodeUnpublishVolume.

2021-03-23 09:43 UTC, avalluri commented on pkg/hostpath/server.go
> -	glog.V(5).Infof("GRPC request: %+v", protosanitizer.StripSecrets(req))
> Let's keep the behavior at level 3 as it is:
> 
> * don't log `Probe`
> * log as plain text as before

@pohly  You mean logging the method name, or logging full request in plain text?

Does this looks right?:
```
	resp, err := handler(ctx, req)
	if info.FullMethod == "/csi.v1.Identity/Probe" {
		glog.V(5).Infof("GRPC call: %s", info.FullMethod)
		return resp, err
	}
	glog.V(3).Infof("GRPC call: %s", info.FullMethod)
	if glog.V(5) {
		// Strip secrets from request before logging
		json.Unmarshal([]byte(protosanitizer.StripSecrets(req).String()), req)
		logGRPCJson(info.FullMethod, req, resp, err)
	}
```

2021-03-23 13:07 UTC, pohly commented on pkg/hostpath/server.go
> -	glog.V(5).Infof("GRPC request: %+v", protosanitizer.StripSecrets(req))
I mean that at level 5, we log `Probe` like any other method call. We don't return early either.

```

func logGRPC(ctx context.Context, req interface{}, info *grpc.UnaryServerInfo, handler grpc.UnaryHandler) (interface{}, error) {
    pri := 3
    if info.FullMethod == "/csi.v1.Identity/Probe" {
                // This call occurs frequently, therefore it only gets log at level 5.
		pri = 5
    }
    glog.V(pri).Infof("GRPC call: %s", info.FullMethod)

    var strippedReq interface{}
    v5 := glog.V(5)
    if v5.Enabled() {
          strippedReq = protosanitizer.StripSecrets(req)
          v5.Infof("GRPC request: %+v", strippedReq)
    }
    resp, err := handler(ctx, req)
    if err != nil {
        // Always log errors. Probably not useful though without the method name?!
	glog.Errorf("GRPC error: %v", err)
    }
    if v5.Enabled() {
        strippedResp := protosanitizer.StripSecrets(resp)
	v5.Infof("GRPC response: %+v", strippedResp)
   
        logGRPCJson(info.FullMethod, strippedReq, strippedResp, err)
    }

    return resp, err
}
```

2021-03-24 09:46 UTC, avalluri commented on pkg/hostpath/server.go
> -	glog.V(5).Infof("GRPC request: %+v", protosanitizer.StripSecrets(req))
@pohly I took your changes with minor fixes. Thanks.

2021-03-24 09:47 UTC, avalluri commented on go.sum
> -github.com/onsi/ginkgo v1.11.0 h1:JAKSXpt1YjtLA7YpPiqO9ss6sNXEsPfSGdwN0UHqzrw=
This result of Go version update, which is not valid anymore.

2021-03-24 09:48 UTC, avalluri commented on cmd/hostpathplugin/main.go
> +	disableAttach = flag.Bool("disable-attach", false, "Disables RPC_PUBLISH_UNPUBLISH_VOLUME capability.")
Agreed, and changed as suggested.

2021-03-24 09:48 UTC, avalluri commented on pkg/hostpath/controllerserver.go
> +	topologies := []*csi.Topology{{
Moved to a separate commit.

2021-03-24 09:51 UTC, avalluri commented on pkg/hostpath/controllerserver.go
> +	v.VolAttached = false
Removed this unneeded comment, and added missing checks for validating volume lifecycle calls.

2021-03-24 09:57 UTC, avalluri commented on pkg/hostpath/controllerserver.go
> +	}
Added all these failure checks to the code:
 - NodeSageVolume with no prior ControllerPublishVolume(only if `--enable-attach`)
 - NodePublishVolume with no prior NodeStageVolume
 - NodeUnstageVolume with no prior NodeUnpublishVolume
 - ControllerUnpublishVolume with no prior NodeUn{stage,pulish}Volume
 - DeleteVolume with no prior NodeUn{stage,pulish}Volume and no ControllerUnpublishVolume(only if `--enable-attach`)

2021-03-24 09:58 UTC, avalluri commented on pkg/hostpath/controllerserver.go
> +	}
Done.

2021-03-25 11:56 UTC, pohly requested changes

2021-03-25 11:56 UTC, pohly commented on pkg/hostpath/server.go
> +	if v5 {
Oh, "glog" literally is github.com/golang/glog. Then the check has to be like this.

Another, separate enhancement would be to replace that with klog/v2.

2021-03-25 11:56 UTC, pohly commented on pkg/hostpath/server.go
> +		// convert back to the object, os that logGRPCJson
Language?

2021-03-25 11:56 UTC, pohly commented on pkg/hostpath/server.go
> +		logGRPCJson(info.FullMethod, req, resp, err)
If this worked, it would modify "resp", the value returned to the caller. We can't do that.

But I also don't think it actually works as intended: `json.Umarshal` just adds values to the object. It does not clear unset ones. That means that secrets remain set.

I think we shouldn't strip secrets in the JSON output. The normal output demonstrates how to do it properly (thus satisfying the goal of showing how to write CSI drivers) and the JSON output is for debugging where we actually may want to see the secrets.

To be on the safe side, we can add a warning to the main README, next to the warning that this driver is just a demo.

2021-03-25 11:56 UTC, pohly commented on pkg/hostpath/controllerserver.go
> +		return nil, status.Errorf(codes.Internal, "Volume '%s' is still used(attached: %v, staged: %v, published: %v) by '%s' node",
Space before opening bracket, please.

2021-03-25 11:56 UTC, pohly commented on pkg/hostpath/controllerserver.go
> +		return nil, status.Errorf(codes.Internal, "Volume '%s' is still used(staged: %v, published: %v) by '%s' node",
Space before bracket.

2021-03-25 11:56 UTC, pohly commented on pkg/hostpath/hostpath.go
> +type volumeState string
Is this used anywhere?

2021-03-25 11:56 UTC, pohly commented on pkg/hostpath/hostpath.go
> +	ReadOnlyAttach bool       `json:"ReadOnlyAttach"`
JSON names usually start with lower case.

2021-03-25 19:46 UTC, avalluri commented on pkg/hostpath/server.go
> +		logGRPCJson(info.FullMethod, req, resp, err)
> If this worked, it would modify "resp", the value returned to the caller. We can't do that.
> 
> But I also don't think it actually works as intended: `json.Umarshal` just adds values to the object. It does not clear unset ones. That means that secrets remain set.

Yes, you are right. It's my bad I ignored this completely. I should have written the unmarshalled into a new copy.

2021-03-25 20:18 UTC, avalluri commented on pkg/hostpath/server.go
> +		logGRPCJson(info.FullMethod, req, resp, err)
> I think we shouldn't strip secrets in the JSON output. The normal output demonstrates how to do it properly (thus satisfying the goal of showing how to write CSI drivers) and the JSON output is for debugging where we actually may want to see the secrets.
> 
> To be on the safe side, we can add a warning to the main README, next to the warning that this driver is just a demo.

Changed as suggested to log secret fields in JSON format. And also added a README warning.

2021-03-25 20:18 UTC, avalluri commented on pkg/hostpath/controllerserver.go
> +		return nil, status.Errorf(codes.Internal, "Volume '%s' is still used(attached: %v, staged: %v, published: %v) by '%s' node",
Done

2021-03-25 20:18 UTC, avalluri commented on pkg/hostpath/controllerserver.go
> +		return nil, status.Errorf(codes.Internal, "Volume '%s' is still used(staged: %v, published: %v) by '%s' node",
Done.

2021-03-25 20:19 UTC, avalluri commented on pkg/hostpath/hostpath.go
> +type volumeState string
No, This should be removed. Done

2021-03-25 20:20 UTC, avalluri commented on pkg/hostpath/hostpath.go
> +	ReadOnlyAttach bool       `json:"ReadOnlyAttach"`
Changed all field names to camelcase.

2021-03-26 07:22 UTC, pohly commented on pkg/hostpath/hostpath.go
> +	ReadOnlyAttach bool       `json:"ReadOnlyAttach"`
I still see `ReadOnlyAttach`?

2021-03-26 09:08 UTC, avalluri commented on pkg/hostpath/hostpath.go
> +	ReadOnlyAttach bool       `json:"ReadOnlyAttach"`
Sorry, I fixed it now.

2021-03-27 17:38 UTC, avalluri commented
/retest

2021-03-29 21:23 UTC, pohly commented
/lgtm

/assign @msau42 

For approval.

2021-03-30 23:01 UTC, msau42 commented on cmd/hostpathplugin/main.go
> +	proxyEndpoint = flag.String("proxy-endpoint", "", "Instead of running the CSI driver code, just proxy connections from csiEndpoint to the given listening socket.")
Do we need some documentation on how to use this proxyEndpoint?

2021-03-31 07:17 UTC, pohly commented on cmd/hostpathplugin/main.go
> +	proxyEndpoint = flag.String("proxy-endpoint", "", "Instead of running the CSI driver code, just proxy connections from csiEndpoint to the given listening socket.")
I can't imagine who besides us in k/k e2e test would want to use this, so I don't think that we need end-user documentation in the README for this. For those who want to know more, there's always the source code...

2021-03-31 07:22 UTC, pohly commented on pkg/hostpath/server.go
> +		logGRPCJson(info.FullMethod, req, resp, err)
Two reason:
- It's technically complicated because protosanitizer.StripSecrets does not construct new objects, it just wraps the existing ones with a custom String implementation. Therefore a simple `json.Marshal(protosanitizer.StripSecrets(resp))` will still include secrets and more complicated code would be needed.
- This is indeed for verification in mock e2e tests. I don't know whether we have any which look at secrets, but we might, so conceptually it seems better to me to include secrets.

2021-03-31 16:45 UTC, msau42 commented on README.md
> +*WARNING: This driver is just a demo implementation.
I would add that this driver is used for CI testing and has many fake implementations and other non-standard best practices, and should not be used as an example of how to write a real driver.

2021-03-31 16:45 UTC, msau42 commented on cmd/hostpathplugin/main.go
> +	proxyEndpoint = flag.String("proxy-endpoint", "", "Instead of running the CSI driver code, just proxy connections from csiEndpoint to the given listening socket.")
I will disagree that just because something is for internal testing we shouldn't document it (and note it as such). It doesn't have to be elaborate, and even just a pointer to the tests using it could be enough.

2021-03-31 16:45 UTC, msau42 commented on pkg/hostpath/server.go
> +		logGRPCJson(info.FullMethod, req, resp, err)
Thanks, can we document this in the code?

It is also a major change from previous behavior. Would it make sense that we make this a new major release of the hostpath driver with some big warnings that this driver should no longer be used as an example for writing a driver or running in production (however unlikely we think it may be).

2021-03-31 18:57 UTC, pohly commented on pkg/hostpath/server.go
> +		logGRPCJson(info.FullMethod, req, resp, err)
A major version bump indeed seems appropriate. Let's see whether I can add the label as a reminder:

/kind api-change

2021-03-31 18:58 UTC, pohly commented on README.md
> +*WARNING: This driver is just a demo implementation.
Agreed.

2021-03-31 19:01 UTC, pohly commented on cmd/hostpathplugin/main.go
> +	proxyEndpoint = flag.String("proxy-endpoint", "", "Instead of running the CSI driver code, just proxy connections from csiEndpoint to the given listening socket.")
Where would you put that?

The main README.md has no documentation whatsoever about driver command line parameters. I'm really not keen on having to document all existing parameters and adding just this one there would be inconsistent. Documenting all parameters is fine and appropriate for the sidecars, but for this driver I still think it is overkill.

2021-03-31 19:55 UTC, avalluri commented on README.md
> +*WARNING: This driver is just a demo implementation.
I rephrased the warning in the ReadME as @msau42 suggested:

`
*WARNING: This driver is just a demo implementation and is used for CI testing. This has many fake implementations and other non-standard best practices, and should not be used as an example of how to write a real driver.
`

2021-04-01 14:24 UTC, avalluri commented on pkg/hostpath/server.go
> +		logGRPCJson(info.FullMethod, req, resp, err)
I added this comment to the source code:

> * It's technically complicated because protosanitizer.StripSecrets does not construct new objects, it just wraps the existing ones with a custom String implementation. Therefore a simple `json.Marshal(protosanitizer.StripSecrets(resp))` will still include secrets because it reads fields directly and more complicated code would be needed.
> * This is indeed for verification in mock e2e tests. I don't know whether we have any which look at secrets, but we might, so conceptually it seems better to me to include secrets.

2021-04-01 15:14 UTC, pohly commented
Some of the new comments could be improved, but I am okay with letting that stand as it is, so

/lgtm

from me.

2021-04-01 15:14 UTC, pohly commented
/retest

2021-04-02 22:52 UTC, msau42 commented on cmd/hostpathplugin/main.go
> +	proxyEndpoint = flag.String("proxy-endpoint", "", "Instead of running the CSI driver code, just proxy connections from csiEndpoint to the given listening socket.")
A comment above this flag is fine with me.

2021-04-02 22:52 UTC, msau42 commented on cmd/hostpathplugin/main.go
> +	if *proxyEndpoint != "" {
General question, it seems like this proxy is standalone and doesn't use any methods of the hostpath driver. Would it make sense to have it be a separate binary?

2021-04-03 18:24 UTC, pohly commented on cmd/hostpathplugin/main.go
> +	if *proxyEndpoint != "" {
We discussed various options when adding this functionality to the mock driver binary; the situation was the same. We considered the whole range (separate repo, separate binary in its own image, separate binary in the same image, new feature in an existing binary and image) and in the end agreed that the last option was the simplest approach.

Everything else comes with additional overhead, both for managing the releases and also regarding image sizes needed during testing (Go runtime only linked onced, same image used for multiple tests).

2021-04-03 18:36 UTC, pohly commented on cmd/hostpathplugin/main.go
> +	proxyEndpoint = flag.String("proxy-endpoint", "", "Instead of running the CSI driver code, just proxy connections from csiEndpoint to the given listening socket.")
@avalluri can you add this section after "Pre-requisite"?

Features
=======

The driver can provide empty directories that are backed by the same filesystem as EmptyDir volumes. In addition, it can provide raw block volumes that are backed by a single file in that same filesystem and bound to a loop device.

[Various command line parameters](https://github.com/kubernetes-csi/csi-driver-host-path/blob/master/cmd/hostpathplugin/main.go) influence the behavior of the driver. This is relevant in particular for the end-to-end testing that this driver is used for in Kubernetes.

Usually, the driver implements all CSI operations itself. When deployed with the `-proxy-endpoint` parameter, it instead proxies all incoming connections for a CSI driver that is [embedded inside the Kubernetes E2E test suite](https://github.com/kubernetes/kubernetes/tree/master/test/e2e/storage/drivers/csi-test) and used for mocking a CSI driver [with callbacks provided by certain tests](https://github.com/kubernetes/kubernetes/blob/5ad79eae2dcbf33df3b35c48ec993d30fbda46dd/test/e2e/storage/csi_mock_volume.go#L110).

2021-04-06 07:04 UTC, avalluri commented on cmd/hostpathplugin/main.go
> +	if *proxyEndpoint != "" {
> A comment above this flag is fine with me.

@msau42 Added the comment explaining the usage of this nuew flag.

2021-04-06 07:07 UTC, avalluri commented on cmd/hostpathplugin/main.go
> +	proxyEndpoint = flag.String("proxy-endpoint", "", "Instead of running the CSI driver code, just proxy connections from csiEndpoint to the given listening socket.")
> @avalluri can you add this section after "Pre-requisite"?
> 
Done. Added the ['Features'  section](https://github.com/kubernetes-csi/csi-driver-host-path/pull/260/commits/8a3b3c522b28ee501277666afff3db0d01f32e2a).

2021-04-06 07:37 UTC, pohly approved these changes
/lgtm

2021-04-06 16:47 UTC, msau42 commented
/approve

Thanks!

2021-04-06 16:48 UTC, merged