storage capacity e2e test
kubernetes-csi/csi-driver-host-path pull request #265
Opened 2021-03-24 16:47 UTC by pohly

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

This enables testing CSIStorageCapacity publishing if https://github.com/kubernetes/kubernetes/pull/100537 gets merged.

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

2021-03-24 16:48 UTC, pohly commented
/hold

Let's first merge https://github.com/kubernetes/kubernetes/pull/100537. The test-driver.yaml changes cause no harm without it, but also don't make much sense.

2021-03-24 17:18 UTC, verult commented
/assign

2021-03-25 02:00 UTC, verult requested changes

2021-03-25 08:20 UTC, pohly commented on deploy/kubernetes-distributed/test-driver.yaml
> +    capacity: true
I was also using the file directly when invoking tests manually, so a valid value is more useful. But a comment makes sense - added

2021-03-25 08:20 UTC, pohly commented on deploy/kubernetes-distributed/test-driver.yaml
> +    CSILocalStorage: true
Done.

2021-03-25 08:40 UTC, pohly commented on deploy/kubernetes-distributed/deploy.sh
> +else
Added, with truncation in case that there is a long list of objects. I also added printing of the expected API version. It now looks like this:
```
rolebinding.rbac.authorization.k8s.io/csi-provisioner-role-cfg unchanged
csistoragecapacities.v1alpha1.storage.k8s.io:
   Warning: storage.k8s.io/v1alpha1 CSIStorageCapacity is deprecated in v1.21+, unavailable in v1.24+; use storage.k8s.io/v1beta1 CSIStorageCapacity
   NAME          CREATED AT
   csisc-665c6   2021-03-24T14:20:03Z
   csisc-972hh   2021-03-24T15:56:18Z
   ...
deploying with CSIStorageCapacity v1alpha1: true
deploying hostpath components
```

Or with `CSI_PROVISIONER_TAG=canary`:
```
rolebinding.rbac.authorization.k8s.io/csi-provisioner-role-cfg created
csistoragecapacities.v1beta1.storage.k8s.io:
   No resources found in default namespace.
deploying with CSIStorageCapacity v1beta1: true
```

2021-03-26 14:31 UTC, pohly commented on deploy/kubernetes-distributed/deploy.sh
> +else
I moved this fix into a separate PR: https://github.com/kubernetes-csi/csi-driver-host-path/pull/266

2021-03-26 15:52 UTC, pohly commented
/hold cancel

2021-03-29 20:43 UTC, verult commented
LGTM, will add label after rebase

2021-03-30 07:55 UTC, pohly commented
@verult rebased, please LGTM.

2021-03-30 19:04 UTC, verult commented
/lgtm

2021-04-07 01:26 UTC, msau42 commented
/approve

2021-04-07 08:06 UTC, pohly commented
/approve

2021-04-07 08:35 UTC, merged