Add more missing features from mock csi driver
kubernetes-csi/csi-driver-host-path pull request #269
Opened 2021-03-29 07:45 UTC by avalluri

**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
With the combination of #260,  this enables in replacing the Mock CSI driver with host-path driver in Kubernetes E2E testing as described in #247.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
This PR is based on changes in #260.

**Does this PR introduce a user-facing change?**:

```release-note

Added support for configuring the maximum number of volumes that could be attached on a node using `--attach-limit`.

```

2021-03-29 21:23 UTC, pohly commented
/ok-to-test

2021-04-07 16:20 UTC, pohly commented on pkg/hostpath/hostpath.go
> -	capacity     Capacity
Capacity must be protected by the mutex. That is no longer obvious.

Perhaps a better solution for it would be to have a read-only copy of the total capacity in `config` and dynamically calculate the remaining capacity by substracting the size of all current volumes.

2021-04-07 16:23 UTC, pohly reviewed
The rest looks okay to me.

2021-04-08 14:02 UTC, pohly commented on pkg/hostpath/hostpath.go
> -	capacity     Capacity
I have another, older PR which also adds another parameter and partly fixed the capacity check: https://github.com/kubernetes-csi/csi-driver-host-path/pull/253

Here's a proposal:
- I change how capacity is tracked in that PR.
- I add your config struct commit.
- I add my new value to it.

Once that is merged, you can rebase your PR.

2021-04-08 18:17 UTC, pohly commented
/test pull-kubernetes-csi-csi-driver-host-path-distributed-on-kubernetes-master

2021-04-08 19:24 UTC, avalluri commented on pkg/hostpath/hostpath.go
> -	capacity     Capacity
> @avalluri: The following test **failed**, say `/retest` to rerun all failed tests:

I will check what caused the failure.

2021-04-08 19:24 UTC, avalluri commented
> @avalluri: The following test **failed**, say `/retest` to rerun all failed tests:

I will check what caused the failure.

2021-04-08 19:25 UTC, avalluri commented on pkg/hostpath/hostpath.go
> -	capacity     Capacity
Sounds good,, Once your PR is ready, I will rebase mine.

2021-04-08 20:08 UTC, pohly commented
> I will check what caused the failure.

I have a fix for the install issue in https://github.com/kubernetes-csi/csi-driver-host-path/pull/253. The code itself probably also needed some of the changes there.

2021-04-09 10:17 UTC, avalluri commented
/retest

2021-04-09 11:45 UTC, pohly commented
/test pull-kubernetes-csi-csi-driver-host-path-distributed-on-kubernetes-master

2021-04-09 11:48 UTC, pohly commented on cmd/hostpathplugin/main.go
> -		c := hostpath.Capacity{}
This initialization here must not get dropped. Dropping it causes a nil-map access when a parameter gets set.

https://github.com/kubernetes-csi/csi-driver-host-path/pull/253 changes `hostpath.Capacity` so that a nil pointer is okay.

2021-04-09 16:34 UTC, avalluri commented
Rebased on #253

2021-04-09 16:35 UTC, avalluri commented
/test pull-kubernetes-csi-csi-driver-host-path-distributed-on-kubernetes-master

2021-04-16 11:28 UTC, avalluri commented
/test pull-kubernetes-csi-csi-driver-host-path-distributed-on-kubernetes-master

2021-04-16 13:07 UTC, pohly commented
`External Storage [Driver: hostpath.csi.k8s.io] [Testpattern: Dynamic PV (immediate binding)] topology should provision a volume and schedule a pod with AllowedTopologies` is a new failure that also occurs without this PR (https://github.com/kubernetes-csi/csi-driver-host-path/issues/274). We can ignore it for this PR.

2021-04-16 13:10 UTC, pohly requested changes
The code is fine, but the release notes entry only reflects one of the four feature commits. Please also mention the other new options.

2021-04-19 06:59 UTC, avalluri commented
> The code is fine, but the release notes entry only reflects one of the four feature commits. Please also mention the other new options.

Updated the release notes with two other command-line options.

2021-04-19 08:44 UTC, pohly approved these changes
/lgtm
/approve

2021-04-19 08:46 UTC, merged

2022-01-14 14:59 UTC, gnufied commented on cmd/hostpathplugin/main.go
> +	flag.BoolVar(&cfg.EnableVolumeExpansion, "node-expand-required", true, "Enables NodeServiceCapability_RPC_EXPAND_VOLUME capacity.")
This variable and configuration option is strangely named. It says "node-expand-required" but in truth, it controls entire volume expansion feature. I would like us to rename this.

2022-01-15 16:04 UTC, pohly commented on cmd/hostpathplugin/main.go
> +	flag.BoolVar(&cfg.EnableVolumeExpansion, "node-expand-required", true, "Enables NodeServiceCapability_RPC_EXPAND_VOLUME capacity.")
I haven't looked into it, but that sounds reasonable. Can you submit a PR?