[WIP] Deploy Canary Snapshot Controller When Kubernetes Version in Latest
kubernetes-csi/csi-driver-host-path pull request #312
Opened 2021-06-03 11:29 UTC by Kartik494

**What type of PR is this?**

> /kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes https://github.com/kubernetes-csi/external-snapshotter/issues/516

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

2021-06-03 11:30 UTC, Kartik494 commented
/release-note-none

2021-06-04 06:34 UTC, pohly requested changes

2021-06-04 06:34 UTC, pohly commented on release-tools/prow.sh
> +  eval current=${SNAPSHOT_CONTROLLER_YAML}
Why `eval`?

2021-06-04 06:34 UTC, pohly commented on release-tools/prow.sh
>    if [[ ${REPO_DIR} == *"external-snapshotter"* ]]; then
Please update both code paths to use `kubectl --kustomize` and the same code. The only difference between them is which image gets used.

2021-06-04 06:34 UTC, pohly commented on release-tools/prow.sh
> +        # the root of a kustomization.
How do you know that we have a local file here? The if check doesn't match.

2021-06-08 06:39 UTC, Kartik494 commented on release-tools/prow.sh
>    if [[ ${REPO_DIR} == *"external-snapshotter"* ]]; then
@pohly  Thanks for the suggestions , i will be updating as suggested.

2021-06-09 12:45 UTC, Kartik494 commented on release-tools/prow.sh
> +        # the root of a kustomization.
@pohly  I used the approach here to store the yaml file of external-snapshotter  in a temp dir and then made a kustomization file that will configure and  patch the image file for master to use canary deployment . The implementation for the same is not yet completed will do the same ASAP . 
 `TEMP_DIR="$( mktemp -d )"` 
` trap 'rm -rf ${TEMP_DIR}' EXIT`

2021-09-01 04:54 UTC, Kartik494 commented
Closing this PR in reference for this  
https://github.com/kubernetes-csi/external-snapshotter/issues/516

2021-09-01 04:54 UTC, Kartik494 commented
/close

2021-09-01 04:54 UTC, closed without merging