fix: Missing a piece of the URL, for the CRD installation
kubernetes-csi/csi-driver-host-path pull request #396
Opened 2023-02-19 07:58 UTC by xiangpingjiang

**What type of PR is this?**

> /kind bug

**What this PR does / why we need it**:
fix : Missing a piece of the URL, for the CRD installation
**Which issue(s) this PR fixes**:

Fixes #367 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

2023-02-19 11:53 UTC, xiangpingjiang commented
/ok-to-test

2023-02-19 11:56 UTC, xiangpingjiang commented
/ok-to-test

2023-02-19 11:59 UTC, andyzhangx approved these changes
/ok-to-test
/lgtm

2023-02-19 13:58 UTC, xiangpingjiang commented
/assign @pohly

2023-02-19 17:07 UTC, pohly requested changes
/lgtm cancel

2023-02-19 17:07 UTC, pohly commented on docs/deploy-1.17-and-later.md
> +quay.io/k8scsi/snapshot-controller:v6.2.1,
There is no such image.

2023-06-21 09:30 UTC, pohly commented
/close

2023-06-21 09:30 UTC, closed without merging