[WIP] Implement CSI SnapshotMetadata service
kubernetes-csi/csi-driver-host-path pull request #569
Opened 2024-10-15 12:10 UTC by PrasadG193

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

Pending items:
[] Support for VARIABLE sized block metadata response
[] Do we need to hide this behind featureflag till external-snapshot-metadata alpha is released?

**Does this PR introduce a user-facing change?**:

```release-note

```

2024-10-25 02:11 UTC, xing-yang commented
/assign
/assign @bswartz

2024-10-28 22:04 UTC, carlbraganza commented on pkg/hostpath/snapshotmetadata.go
> +	}
This is a gRPC `OUT_OF_RANGE` error that must be forwarded to the client.

2024-10-28 22:06 UTC, carlbraganza commented on pkg/hostpath/snapshotmetadataserver.go
> +	}()
The error returned by the function may be significant and require a specific gRPC code - e..g. `OUT_OF_RANGE`.

I suggest not using a goroutine but instead us a synchronous I/O access pattern - i.e. equivalent to`Open`, `Seek`, `Read` and `Close`.

2024-10-28 22:08 UTC, carlbraganza commented on pkg/hostpath/snapshotmetadataserver.go
> +		return status.Error(codes.Internal, "Cannot find the snapshot")
This should be `codes.NotFound`.

2024-10-31 15:03 UTC, xing-yang commented
This is a new feature. Please add a release note.
Can you add a note in the PR description that this is a sample implementation, and not for production use.

2024-10-31 15:03 UTC, xing-yang commented on pkg/hostpath/snapshotmetadata.go
> +
Can you add a note here that this is a sample implementation, and not for production use.

2024-11-07 14:03 UTC, PrasadG193 commented
@carlbraganza @xing-yang I've addressed the feedback. PTAL

2024-11-14 18:53 UTC, carlbraganza commented
@PrasadG193 LGTM!  Need approval from @xing-yang or @bswartz

2024-12-02 13:30 UTC, iPraveenParihar requested changes

2024-12-02 13:30 UTC, iPraveenParihar commented on pkg/hostpath/snapshotmetadataserver.go
> +			if err == io.EOF {
```suggestion
			if errors.Is(cbErr, io.EOF) {
```

2024-12-02 13:30 UTC, iPraveenParihar commented on pkg/hostpath/snapshotmetadataserver.go
> +			if err == io.EOF {
```suggestion
			if errors.Is(cbErr, io.EOF) {
```

2024-12-02 17:20 UTC, xing-yang commented
Can you add your testing steps?

2024-12-04 16:13 UTC, Rakshith-R commented
> Can you add your testing steps?

hey @xing-yang ,

@PrasadG193 is on vacation and will be back thursday.

He had developed a client to test the new RPCs https://github.com/PrasadG193/external-snapshot-metadata-client 
which has been adopted as a tool in this pr https://github.com/kubernetes-csi/external-snapshot-metadata/pull/64 

We are creating a gh action that adds simple e2e
https://github.com/kubernetes-csi/external-snapshot-metadata/issues/67 
```
Add a github action that:
- checkout repository
- sets up minikube
- builds latest sidecar image
- deploys csi-driver-hostpath driver resources
- runs simple e2e tests to create pvc, pod and snapshots and to write data.
- run client to verify working of both RPCs.
```

Sample run https://github.com/Rakshith-R/external-snapshot-metadata/actions/runs/12163453092/job/33922692908
(with the fix @iPraveenParihar has suggested above)

2024-12-04 16:33 UTC, carlbraganza commented on pkg/hostpath/snapshotmetadataserver.go
> +	}
@PrasadG193 Is this really necessary? Most CSI drivers that make volume snapshots do so regardless of the access mode. It imposes an additional hurdle for testing.

2024-12-05 14:56 UTC, Rakshith-R commented on pkg/hostpath/snapshotmetadataserver.go
> +	}
volume mode can be converted from filesystem to block ex:
filesystem parent PVC -> snapshot -> annotate VSC to permit conversion of volumeMode -> restore into block mode PVC.

https://kubernetes-csi.github.io/docs/prevent-volume-mode-conversion.html

Backup solution will use this route to backup filesystem PVCs mounted on block devices provided by storage solutions.

2024-12-09 12:56 UTC, PrasadG193 commented
@xing-yang I have documented complete test plan along with steps to deploy csi driver with external-snapshot-metadata here - https://gist.github.com/PrasadG193/1fab082f03bbdb7db25a41ed17b7e7c1

2024-12-10 06:52 UTC, PrasadG193 commented on pkg/hostpath/snapshotmetadataserver.go
> +	}
thanks, I will test and address that

2024-12-10 11:27 UTC, Rakshith-R commented on pkg/hostpath/snapshotmetadataserver.go
> +	}
> volume mode can be converted from filesystem to block ex: filesystem parent PVC -> snapshot -> annotate VSC to permit conversion of volumeMode -> restore into block mode PVC.
> 
> https://kubernetes-csi.github.io/docs/prevent-volume-mode-conversion.html
> 
> Backup solution will use this route to backup filesystem PVCs mounted on block devices provided by storage solutions.

We discussed this offline.

Hostpath driver creates a directory for a filesystem PVC
and creates a block device for block PVC.
https://github.com/kubernetes-csi/csi-driver-host-path/blob/2211f6ddc9ebf9cb23a3f29021ccc55b63e8f523/pkg/hostpath/hostpath.go#L185-L204

Hence, we cannot convert a directory part of a filesystem into block device.

2024-12-10 12:35 UTC, iPraveenParihar commented
LGTM! @PrasadG193

2024-12-11 18:17 UTC, bswartz requested changes
Overall this looks pretty good. There are some inefficient bits of code but for a proof-of-concept it seems fine. I found one bug with error handling.

2024-12-16 09:48 UTC, PrasadG193 commented on pkg/hostpath/snapshotmetadata.go
> +		base.Close()
AAh, I missed moving the close to L102 after refactoring the code. I've fixed this now

2024-12-16 20:35 UTC, bswartz approved these changes
/lgtm

2024-12-17 17:33 UTC, pnhoang75 commented on cmd/hostpathplugin/main.go
> +		fmt.Printf("invalid snapshot-metadata-block-type passed, please pass one of the - FIXED_LENGTH, VARIABLE_LENGTH")
nit: use upper case for beginning of the error/exit message to conform with other error messages in the file.

2024-12-18 17:57 UTC, bswartz approved these changes
/lgtm

2024-12-18 17:58 UTC, xing-yang commented
/approve

2024-12-18 18:32 UTC, merged